# vi: se sw=2 sts=2 ts=2 et:
image: navikt/miaindekserer
replicas:
  min: 1
  max: 1
port: 1234

healthcheck:
  liveness:
    path: /isAlive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /isReady
    initialDelay: 60
    timeout: 10

resources:
  limits:
    cpu: 6
    memory: 768Mi
  requests:
    memory: 512Mi


prometheus:
  enabled: true
  path: /metrics

team: oppfolging

fasitResources:
  used:
    - alias: mia_elasticsearch_user
      resourceType: credential
      propertyMap:
        username: esUser
        password: esPassword

    - alias: appdynamics
      resourceType: applicationproperties

    - alias: unleash-api
      resourceType: restservice

    - alias: pam-ad-internal-url
      resourceType: restservice
      propertyMap:
        url: pamUrl

alertProfiles:
 - basic
