# vi: se sw=2 sts=2 ts=2 et:
image: docker.adeo.no:5000/fo/miaindekserer
replicas:
  min: 1
  max: 1
port: 8080

healthcheck:
  liveness:
    path: /isAlive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /isReady
    initialDelay: 60
    timeout: 10

resources:
  limits:
    cpu: 6
    memory: 768Mi
  requests:
    memory: 256Mi

prometheus:
  enabled: true
  path: /metrics

team: oppfolging

fasitResources:
  used:
    - alias: mia_elasticsearch_user
      resourceType: credential
      propertyMap:
        username: ES_USER
        password: ES_PASSWORD

    - alias: appdynamics
      resourceType: applicationproperties

    - alias: unleash-api
      resourceType: restservice

alertProfiles:
 - basic
